name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  testjob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      
      - name: Run tests
        run: |
          pip install -r requirements.txt
          pytest test_app.py

  deploy:
    runs-on: ubuntu-latest
    needs: testjob

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        if: success()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/my-project
            git pull origin main
            systemctl restart farm.service
            systemctl status farm.service
